services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: timer
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - "8008:8080"
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev" ]
